### ISSUE TITLE
after installing Full Next Search (Main) I can't access my settings anymore

### ISSUE THREAD

**Issue by olli0815** [nextcloud/fullnextsearch_elasticsearch#2]

**Comment by daita** [comment]
Should be fixed in 0.3.1. Please upgrade.

**Comment by olli0815** [comment]
Hi,

still no luck. After testing 0.31.
When FNS is enabled I get an internal server error when I try do access the Settings.

**Comment by daita** [comment]
you upgraded all 3 apps ? fns, fns_elasticsearch and files_fns ?

Do you have more details in the nextcloud logs ?

**Comment by olli0815** [comment]
yes I did, only when try to activate FNS (Main app) I get this:

Exception: template file not found: template:settings.personal

    /usr/share/nextcloud/lib/private/legacy/template.php - line 176: OC\Template\TemplateFileLocator->find('settings.person...')
    /usr/share/nextcloud/lib/private/legacy/template.php - line 87: OC_Template->findTemplate('', 'fullnextsearch', 'settings.person...')
    /usr/share/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php - line 151: OC_Template->__construct('fullnextsearch', 'settings.person...', '')
    /usr/share/nextcloud/apps/fullnextsearch/lib/personal.php - line 42: OCP\AppFramework\Http\TemplateResponse->render()
    /usr/share/nextcloud/lib/private/legacy/app.php - line 706: include('/usr/share/next...')
    /usr/share/nextcloud/lib/private/Settings/Manager.php - line 496: OC_App getForms('personal')
    /usr/share/nextcloud/settings/Controller/CommonSettingsTrait.php - line 89: OC\Settings\Manager->getPersonalSections()
    /usr/share/nextcloud/settings/Controller/CommonSettingsTrait.php - line 42: OC\Settings\Controller\AdminSettingsController->formatPersonalSections('admin', 'logging')
    /usr/share/nextcloud/settings/Controller/CommonSettingsTrait.php - line 120: OC\Settings\Controller\AdminSettingsController->getNavigationParameters('admin', 'logging')
    /usr/share/nextcloud/settings/Controller/AdminSettingsController.php - line 69: OC\Settings\Controller\AdminSettingsController->getIndexResponse('admin', 'logging')
    [internal function] OC\Settings\Controller\AdminSettingsController->index('logging')
    /usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
    /usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\AdminSettingsController), 'index')
    /usr/share/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\AdminSettingsController), 'index')
    /usr/share/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('AdminSettingsCo...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /usr/share/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /usr/share/nextcloud/lib/base.php - line 990: OC\Route\Router->match('/settings/admin...')
    /usr/share/nextcloud/index.php - line 37: OC handleRequest()
    {main}

**Comment by olli0815** [comment]
and 2 other mesages:

--> Array to string conversion at /usr/share/nextcloud/lib/private/App/DependencyAnalyzer.php#356


--> Error | index | Exception: template file not found: template:settings.persona
-- | -- | --

**Comment by daita** [comment]
should be fixed in fns 0.3.2
